using EprRegisterEnrolBackend.AccreditationApplication.Models;

namespace EprRegisterEnrolBackend.AccreditationApplication.Validators;

public class AddOverseasSiteRequestValidator : OverseasSiteRequestValidatorBase<AddOverseasSiteRequest>;