using EprRegisterEnrolBackend.AccreditationApplication.Models;

namespace EprRegisterEnrolBackend.AccreditationApplication.Validators;

public class PromoteOverseasSiteRequestValidator : OverseasSiteRequestValidatorBase<PromoteOverseasSiteRequest>;